spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/spring_sub
    username: arsurei
    password: dlatmdqhd78I@
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      # show_sql: true
        format_sql: true
        use_sql_comments : true
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace


decorator:
  datasource:
    p6spy:
      enable-logging: true